global PosWait;
global SizeWait;
global WaitBar;
global PosKc;
global SizeKc;
global KcBar;

fig = 10;
figure(fig), clf
Hfig = gcf;
set( Hfig, 'Position', [1000, 600, 380, 100], 'Resize', 'off' );

% Define some default colors :
orange     = [0.8 0.7 0.1];
magenta    = [1.0 0.0 1.0];
pink       = [0.8 0.5 0.7];
blue       = [0.2 0.2 1.0];
lightblue  = [0.5 0.7 0.8];
lightgreen = [0.2 0.8 0.3];
white      = [1.0 1.0 1.0];
red        = [1.0 0.0 0.0];
whitepaper = [0.9 0.9 0.6];
black      = [0.0 0.0 0.0];

fx4 = 35;  fy4 = 35;

WaitLabel = uicontrol( Hfig, ...
      'Style', 'text', ...
      'Position', [fx4+15 fy4+20 280 15], ...
      'BackgroundColor', lightblue, ...
      'ForegroundColor', blue, ...
      'Visible', 'on', ...
      'FontSize', [10], ...
      'FontWeight', 'normal', ...
      'HorizontalAlignment', 'center', ...
      'String', 'Wait please ...' );

WaitFrame = uicontrol( Hfig, ...
      'Style', 'frame', ...
      'Position', [fx4+15 fy4+5 280 15], ...
      'Visible', 'on', ...
      'BackgroundColor', white );
PosWait  = [fx4+16 fy4+6 1 13];
SizeWait = 278;
WaitBar = uicontrol( Hfig, ...
      'Style', 'frame', ...
      'Position', PosWait, ...
      'Visible', 'off', ...
      'ForegroundColor', red, ...
      'BackgroundColor', red );
  
KcFrame = uicontrol( Hfig, ...
      'Style', 'frame', ...
      'Position', [fx4+15 fy4-10 280 15], ...
      'Visible', 'on', ...
      'BackgroundColor', white );
PosKc  = [fx4+16 fy4-9 1 13];
SizeKc = 278;
KcBar = uicontrol( Hfig, ...
      'Style', 'frame', ...
      'Position', PosKc, ...
      'Visible', 'off', ...
      'ForegroundColor', blue, ...
      'BackgroundColor', blue );
